checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - vendor/*
        - app/*
        - bin/*
        - web/*
        - spec/*

before_commands:
  - "composer install --prefer-source"
