language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - sudo pip install codecov

before_script:
  - composer install --dev
  - app/console doctrine:database:create --env=test
  - app/console doctrine:migrations:migrate --env=test
  - app/console cache:warmup --env=test

script:
  - phpunit -c app --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

after_success:
  - codecov

notifications:
  email:
    - genvaldartem@gmail.com
