# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    workers:
        cache_busting: ~
    bundles:
      - AppBundle
    filters:
        cssrewrite: ~
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
