ivory_ck_editor:
    default_config: default
    configs:
        default:
            filebrowserBrowseRoute: admin_media_browser
            filebrowserImageBrowseRoute: admin_media_browser
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
            filebrowserUploadRoute: admin_media_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
            filebrowserImageUploadRoute: admin_media_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
                context: images
