imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: assetic.yml }
    - { resource: hwi_oauth.yml }
    - { resource: fos_user.yml }
    - { resource: vich_uploader.yml }
    - { resource: doctrine/doctrine.yml }
    - { resource: doctrine/extensions.yml }
    - { resource: sonata/sonata-admin.yml }
    - { resource: sonata/sonata-admin-orm.yml }
    - { resource: sonata/sonata-block.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'bootstrap_3_layout.html.twig'
            - 'SonataCoreBundle:Form:datepicker.html.twig'
    form_themes:
        - '/backend/item/area_map.html.twig'

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# SensioFrameworkExtra
sensio_framework_extra:
    request:
        converters: true
        auto_convert: false

# A2lix translation form
a2lix_translation_form:
    locales: [uk, ru, en]
    default_required: true
    manager_registry: doctrine

#jms i18n routing bundle
jms_i18n_routing:
    default_locale: %locale%
    locales:
           - uk
           - ru
           - en
    strategy: prefix

#Sonata Seo Bundle
sonata_seo:
    default: sonata.seo.page.default
    encoding: UTF-8
    page:
        title: Lost and Found - Service for announcements of lost and found items
        metas:
            name:
                keywords: бюро знахідок хмельницький  lost found
                description: Бюро знахідок Хмельницький
                robots: index, follow
            http-equiv:
                'Content-Type': text/html; charset=utf-8
            charset:
                UTF-8: ''
