imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

liip_functional_test: ~

doctrine:
    dbal:
        dbname: "%database_name_testing%"
    orm:
        mappings:
            gedmo_loggable: false

stof_doctrine_extensions:
    orm:
        default:
            loggable: false
