app_frontend:
    resource: @AppBundle/Controller/Frontend/
    type:     annotation

app_backend:
    resource: @AppBundle/Controller/Backend/
    type:     annotation
    options: { i18n: false }

app_api:
    resource: "@AppBundle/Resources/config/routing.yml"
    type:     rest
    prefix:   /api/
    options: { i18n: false }

backend:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix:  /admin
    options: { i18n: false }

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    options: { i18n: false }

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /auth/connect
    options: { i18n: false }

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /auth/connect
    options: { i18n: false }

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /auth/connect
    options: { i18n: false }

facebook_login:
    pattern: /auth/check-facebook
    options: { i18n: false }

fos_user_security_logout:
    path: /logout
    defaults: { _controller: FOSUserBundle:Security:logout }
    options: { i18n: false }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    options: { i18n: false }

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
    options: { i18n: false }
