security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_SONATA_ADMIN: ROLE_USER
        ROLE_ADMIN:        [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN:  [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            oauth:
                login_path:   /%locale%/auth/connect/facebook
                failure_path: /%locale%/auth/connect
                check_path:   /%locale%/auth/connect
                provider:     fos_userbundle
                resource_owners:
                    facebook:      /%locale%/auth/check-facebook
                oauth_user_provider:
                    service: app.user.provider
                default_target_path: /
            anonymous: ~
            logout:
                path:   /%locale%/logout
                target: /

    access_control:
        - { path: ^/auth/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/%locale%/admin/, role: ROLE_ADMIN }
        - { path: ^/%locale%/add-lost-item, roles: ROLE_USER }
        - { path: ^/%locale%/add-found-item, roles: ROLE_USER }
        - { path: ^/%locale%/profile/, role: ROLE_USER }
        - { path: ^/%locale%/request-user, role: ROLE_USER }


