security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_SONATA_ADMIN: ROLE_USER
        ROLE_ADMIN:        [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN:  [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            oauth:
                login_path:   facebook_login
                failure_path: hwi_oauth_connect
                check_path:   hwi_oauth_connect
                provider:     fos_userbundle
                resource_owners:
                    facebook: facebook_login
                oauth_user_provider:
                    service: app.user.provider
                default_target_path: homepage
            anonymous: ~
            logout:
                path:   fos_user_security_logout
                target: homepage

    access_control:
        - { path: ^/auth/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/uk/add-lost-item, roles: ROLE_USER }
        - { path: ^/en/add-lost-item, roles: ROLE_USER }
        - { path: ^/ru/add-lost-item, roles: ROLE_USER }
        - { path: ^/uk/add-found-item, roles: ROLE_USER }
        - { path: ^/en/add-found-item, roles: ROLE_USER }
        - { path: ^/ru/add-found-item, roles: ROLE_USER }
        - { path: ^/uk/profile/, roles: ROLE_USER }
        - { path: ^/en/profile/, roles: ROLE_USER }
        - { path: ^/ru/profile/, roles: ROLE_USER }
        - { path: ^/uk/request-user, roles: ROLE_USER }
        - { path: ^/en/request-user, roles: ROLE_USER }
        - { path: ^/ru/request-user, roles: ROLE_USER }
