# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    validator.unique.item_validator:
        class: AppBundle\Validator\Constraints\CheckItemValidator
        tags:
            - { name: validator.constraint_validator, alias: check_item }