#Sonata Seo Bundle
sonata_seo:
    encoding: UTF-8
    page:
        title: Lost and Found - Service for announcements of lost and found items
        metas:
            name:
                keywords: бюро знахідок хмельницький  lost found
                description: Бюро знахідок Хмельницький
                robots: index, follow
            http-equiv:
                'Content-Type': text/html; charset=utf-8
            charset:
                UTF-8: ''
