services:
    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Management", label: "Categories" }
        arguments:
            - ~
            - AppBundle\Entity\Category
            - AppBundle:Backend\CategoryAdmin

    admin.item:
        class: AppBundle\Admin\ItemAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Management", label: "Items" }
        arguments:
            - ~
            - AppBundle\Entity\Item
            - AppBundle:Backend\ItemAdmin

    admin.user:
        class: AppBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "User Management", label: "Users" }
        arguments:
            - ~
            - AppBundle\Entity\User
            - ~

    admin.item_request:
        class: AppBundle\Admin\ItemRequestAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "User Management", label: "Requests to items" }
        arguments:
            - ~
            - AppBundle\Entity\ItemRequest
            - ~

    admin.faq:
        class: AppBundle\Admin\FaqAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "F.A.Q.", label: "Question and answers" }
        arguments:
            - ~
            - AppBundle\Entity\Faq
            - AppBundle:Backend\FaqAdmin
