services:
    app.user.provider:
        class: AppBundle\Security\Provider\AuthProvider
        arguments:
            - @fos_user.user_manager
            - @event_dispatcher

    app.validator.item_area:
        class: AppBundle\Validator\Constraints\ItemAreaValidator
        tags:
            - { name: validator.constraint_validator, alias: item_area }
